2024-09-23 23:13:27,222 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\PythonProjectForUnyversity\Module12\tests_12_4.py", line 20, in test_run
    runner2 = Runner(2)
              ^^^^^^^^^
  File "C:\PythonProjectForUnyversity\Module12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-09-23 23:13:27,224 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\PythonProjectForUnyversity\Module12\tests_12_4.py", line 8, in test_walk
    runner1 = Runner('Bob', -5)
              ^^^^^^^^^^^^^^^^^
  File "C:\PythonProjectForUnyversity\Module12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
